name: conda-envs
channels:
  - conda-forge
  - bioconda
dependencies:  
  # R
  - conda-forge::r-base=4.3.3
  - conda-forge::r-knitr=1.50
  - conda-forge::r-rmarkdown=2.29
  - conda-forge::r-reticulate=1.43.0
  - conda-forge::r-ggplot2=3.5.2

  # CLI
  - conda-forge::quarto=1.8.26